---
# tasks file for mapr-opentsdb

- name: create opentsdb user
  become: yes
  become_user: root
  user: name={{opentsdb_user}} 

- name: install wget
  become: yes
  become_user: root
  yum: name=wget state=present
  environment: '{{proxy_env}}'

- name: install git
  become: yes
  become_user: root
  yum: name=git state=present
  environment: '{{proxy_env}}'

- name: install mapr-hbase
  become: yes
  become_user: root
  yum: name=mapr-hbase-{{hbase[mapr_version]["hbase_version"]}}.{{hbase[mapr_version]["hbase_build"]}} state=present
  environment: '{{proxy_env}}'

- name: install mapr-asynchbase 1.5
  become: yes
  become_user: root
  yum: name=mapr-asynchbase-1.5* state=present
  environment: '{{proxy_env}}'
  when: "'v4.0' in mapr_version"

- name: install mapr-asynchbase 1.7
  become: yes
  become_user: root
  yum: name=mapr-asynchbase-1.7* state=present
  environment: '{{proxy_env}}'
  when: "'v4.1' in mapr_version or 'v5' in mapr_version"

- name: install opentsdb
  become: yes
  become_user: root
  yum: name=https://github.com/OpenTSDB/opentsdb/releases/download/v2.2.0/opentsdb-2.2.0.noarch.rpm state=present
  environment: '{{proxy_env}}'

- name: get zookeeper ensemble
  become: yes
  become_user: "{{mapr_admin_username}}"
  command: maprcli node listzookeepers -noheader
  register: zookeeper
  changed_when: false

- name: update opentsdb user in init script
  become: yes
  become_user: root
  lineinfile: regexp=^USER= line="USER={{opentsdb_user}}" dest=/usr/share/opentsdb/etc/init.d/opentsdb

- name: change ownership of logs directory
  become: yes
  become_user: root
  file: path=/var/log/opentsdb state=directory owner={{opentsdb_user}}

- name: make opentsdb tables home
  become: yes
  become_user: "{{mapr_admin_username}}"
  command: hadoop fs -mkdir -p {{opentsdb_tables_home}}

- name: make opentsdb data directory
  become: yes
  become_user: "{{mapr_admin_username}}"
  command: hadoop fs -chown -R {{opentsdb_user}} {{opentsdb_tables_home}}

- name: install new opentsdb.conf
  become: yes
  become_user: root
  template: src=opentsdb.conf.j2 dest=/usr/share/opentsdb/etc/opentsdb/opentsdb.conf backup=true mode=0644
  notify: restart opentsdb

- name: copy MapR jars (MapR v4.0.x, asynchbase 1.5)
  become: yes
  become_user: root
  command: cp {{item}} /usr/share/opentsdb/lib
  with_items:
    - /opt/mapr/asynchbase/asynchbase-1.5.0/asynchbase-1.5.0-mapr-1501.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/maprfs-4.0.2-mapr.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/maprfs-core-4.0.2-mapr.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/hadoop-common-2.5.1-mapr-1501.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/commons-logging-1.1.3.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/commons-collections-3.2.1.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/maprfs-core-4.0.2-mapr.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/mapr-hbase-4.0.2-mapr.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/hadoop-auth-2.5.1-mapr-1501.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/commons-configuration-1.6.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/commons-lang-2.6.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/json-20080701.jar
  notify: restart opentsdb
  when: "'v4.0' in mapr_version"

- name: copy MapR jars (MapR v4.1.x, asynchbase 1.7)
  become: yes
  become_user: root
  shell: cp {{item}} /usr/share/opentsdb/lib
  with_items:
    - /opt/mapr/asynchbase/asynchbase-1.7.0/asynchbase-1.7.0-mapr-*.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/hadoop-common-2.5.1-mapr-1503.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/commons-logging-1.1.3.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/commons-collections-3.2.1.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/hadoop-auth-2.5.1-mapr-1503.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/commons-configuration-1.6.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/commons-lang-2.6.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/json-20080701.jar
    - /opt/mapr/lib/maprfs-core-4.1.0-mapr.jar
    - /opt/mapr/lib/mapr-hbase-4.1.0-mapr.jar
    - /opt/mapr/lib/maprfs-4.1.0-mapr.jar
    - /opt/mapr/lib/maprfs-core-4.1.0-mapr.jar
  notify: restart opentsdb
  when: "'v4.1' in mapr_version"

- name: copy MapR jars (MapR v5.1.x, asynchbase 1.6)
  become: yes
  become_user: root
  shell: cp {{item}} /usr/share/opentsdb/lib
  with_items:
    - /opt/mapr/asynchbase/asynchbase-1.7.0/asynchbase-1.7.0-mapr-*.jar
    - /opt/mapr/hadoop/hadoop-2.7.0/share/hadoop/common/hadoop-common-2.7.0-mapr-1602.jar
    - /opt/mapr/hadoop/hadoop-2.7.0/share/hadoop/common/lib/commons-logging-1.1.3.jar
    - /opt/mapr/hadoop/hadoop-2.7.0/share/hadoop/common/lib/commons-collections-3.2.2.jar
    - /opt/mapr/hadoop/hadoop-2.7.0/share/hadoop/common/lib/hadoop-auth-2.7.0-mapr-1602.jar
    - /opt/mapr/hadoop/hadoop-2.7.0/share/hadoop/common/lib/commons-configuration-1.6.jar
    - /opt/mapr/hadoop/hadoop-2.7.0/share/hadoop/common/lib/commons-lang-2.6.jar
    - /opt/mapr/hadoop/hadoop-2.7.0/share/hadoop/common/lib/json-20080701.jar
    - /opt/mapr/lib/maprfs-5.1.0-mapr.jar
    - /opt/mapr/lib/mapr-hbase-5.1.0-mapr.jar
    - /opt/mapr/lib/maprfs-5.1.0-mapr.jar
  notify: restart opentsdb
  when: "'v5.1' in mapr_version"

- name: remove non-mapr asynchbase
  become: yes
  become_user: root
  file: path=/usr/share/opentsdb/lib/asynchbase-1.6.0.jar state=absent 

- name: get install helpers
  git: repo=https://github.com/mapr-demos/opentsdb-maprdb-install.git dest=/tmp/opentsdb-maprdb-install force=yes
  environment: '{{proxy_env}}'

- name: update create table script with tables home
  become: yes
  become_user: root
  lineinfile: regexp=^TABLES_PATH line=TABLES_PATH="{{opentsdb_tables_home}}" dest=/tmp/opentsdb-maprdb-install/create_table.sh

- name: create tables
  become: yes
  become_user: '{{opentsdb_user}}'
  command: /tmp/opentsdb-maprdb-install/create_table.sh
  notify: restart opentsdb

- name: create mapr metrics
  become: yes
  become_user: '{{opentsdb_user}}'
  command: tsdb mkmetric mapr.disks.READBYTES mapr.disks.WRITEOPS mapr.disks.WRITEBYTES mapr.disks.READOPS mapr.cpus.CPUTOTAL mapr.cpus.CPUIDLE mapr.cpus.CPUIOWAIT mapr.network.PKTSOUT mapr.network.BYTESOUT mapr.network.PKTSIN mapr.network.BYTESIN mapr.memory.used mapr.mfs.available mapr.mfs.used mapr.rpc.count mapr.rpc.inbytes mapr.rpc.outbytes

- name: enable opentsdb
  become: yes
  become_user: root
  service: name=opentsdb state=started enabled=yes

- name: install warden configuration
  become: yes
  become_user: '{{mapr_admin_username}}'
  copy: src=warden.opentsdb.conf dest=/opt/mapr/conf/conf.d/warden.opentsdb.conf mode=644
