---
# tasks file for mapr-opentsdb

- name: install wget
  yum: name=wget state=present
  environment: proxy_env

- name: install git
  yum: name=git state=present
  environment: proxy_env

- name: install mapr-hbase
  yum: name=mapr-hbase state=present
  environment: proxy_env

- name: install mapr-asynchbase
  yum: name=mapr-asynchbase-{{asynchbase_version}} state=present
  environment: proxy_env

- name: install opentsdb
  yum: name=https://github.com/OpenTSDB/opentsdb/releases/download/v2.1.0RC1/opentsdb-2.1.0RC1.noarch.rpm state=present
  environment: proxy_env

- name: get zookeeper ensemble
  command: maprcli node listzookeepers -noheader
  register: zookeeper

- name: install new opentsdb.conf
  template: src=opentsdb.conf.j2 dest=/usr/share/opentsdb/etc/opentsdb/opentsdb.conf backup=true mode=0644
  notify: restart opentsdb

- name: copy MapR jars
  command: cp {{item}} /usr/share/opentsdb/lib
  with_items:
    - /opt/mapr/asynchbase/asynchbase-1.5.0/asynchbase-1.5.0-mapr-1501.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/maprfs-4.0.2-mapr.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/maprfs-core-4.0.2-mapr.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/hadoop-common-2.5.1-mapr-1501.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/commons-logging-1.1.3.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/commons-collections-3.2.1.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/maprfs-core-4.0.2-mapr.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/mapr-hbase-4.0.2-mapr.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/mapr-hbase-4.0.2-mapr.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/hadoop-auth-2.5.1-mapr-1501.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/commons-configuration-1.6.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/commons-lang-2.6.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/json-20080701.jar
  notify: restart opentsdb

- name: get install helpers
  git: repo=https://github.com/mapr-demos/opentsdb-maprdb-install.git dest=/tmp/opentsdb-maprdb-install
  environment: proxy_env

- name: create tables
  command: /tmp/opentsdb-maprdb-install/create_table.sh
  environment:
    COMPRESSION: NONE
    HBASE_HOME: /opt/mapr/hbase/hbase-{{hbase_version}}
    TSDB_TABLE: /user/mapr/tsdb
    UID_TABLE: /user/mapr/tsdb-uid
    TREE_TABLE: /user/mapr/tsdb-tree
    META_TABLE: /user/mapr/tsdb-meta
  notify: restart opentsdb

- name: create mapr metrics
  command: tsdb mkmetric mapr.disks.READBYTES mapr.disks.WRITEOPS mapr.disks.WRITEBYTES mapr.disks.READOPS mapr.cpus.CPUTOTAL mapr.cpus.CPUIDLE mapr.cpus.CPUIOWAIT mapr.network.PKTSOUT mapr.network.BYTESOUT mapr.network.PKTSIN mapr.network.BYTESIN mapr.memory.used mapr.mfs.available mapr.mfs.used mapr.rpc.count mapr.rpc.inbytes mapr.rpc.outbytes

- name: enable opentsdb
  service: name=opentsdb state=started enabled=yes

