---
# tasks file for mapr-opentsdb

- name: install wget
  yum: name=wget state=present

- name: install git
  yum: name=git state=present

- name: install mapr-hbase
  yum: name=mapr-hbase state=present

- name: install mapr-asynchbase
  yum: name=mapr-asynchbase state=present

- name: install opentsdb
  yum: name=https://github.com/OpenTSDB/opentsdb/releases/download/v2.1.0RC1/opentsdb-2.1.0RC1.noarch.rpm state=present

- name: get zookeeper ensemble
  command: maprcli node listzookeepers -noheader
  register: zookeeper

- name: install new opentsdb.conf
  template: src=opentsdb.conf.j2 dest=/usr/share/opentsdb/etc/opentsdb/opentsdb.conf backup=true mode=0644
  notify: restart opentsdb

- name: copy MapR jars
  command: cp {{item}} /usr/share/opentsdb/lib
  with_items:
    - /opt/mapr/asynchbase/asynchbase-1.5.0/asynchbase-1.5.0-mapr-1501.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/maprfs-4.0.2-mapr.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/maprfs-core-4.0.2-mapr.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/hadoop-common-2.5.1-mapr-1501.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/commons-logging-1.1.3.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/commons-collections-3.2.1.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/maprfs-core-4.0.2-mapr.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/mapr-hbase-4.0.2-mapr.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/mapr-hbase-4.0.2-mapr.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/hadoop-auth-2.5.1-mapr-1501.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/commons-configuration-1.6.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/commons-lang-2.6.jar
    - /opt/mapr/hadoop/hadoop-2.5.1/share/hadoop/common/lib/json-20080701.jar
  notify: restart opentsdb

- name: create tables
  command: /tmp/opentsdb-maprdb-install/create_table.sh
  environment:
    COMPRESSION: NONE
    HBASE_HOME: /opt/mapr/hbase/hbase-{{hbase_version}}
    TSDB_TABLE: /user/mapr/tsdb
    UID_TABLE: /user/mapr/tsdb-uid
    TREE_TABLE: /user/mapr/tsdb-tree
    META_TABLE: /user/mapr/tsdb-meta
  notify: restart opentsdb

- name: download forked tcollector
  get_url: url=https://codeload.github.com/vicenteg/tcollector/zip/master dest=/tmp/tcollector-master.zip
  environment:
    http_proxy: http://172.16.1.58:3128
    https_proxy: http://172.16.1.58:3128
  
- name: unpack tcollector to /opt
  command: chdir=/opt unzip -o /tmp/tcollector-master.zip

- name: enable opentsdb
  service: name=opentsdb state=started enabled=yes

